### ISSUE TITLE
Box Plot

### ISSUE THREAD

**Issue by RoyiAvital** [IoSR-Surrey/MatlabToolbox#1]
Hello,

Is there a way to get Box Plot the way it was?
Namely single file as a MATLAB function with Input?

Thank You.

**Comment by chummersone** [comment]
Unfortunately, I don't think it's possible, sorry. If you could download the file by itself, you would need to maintain the same folder structure, and also download the dependencies (namely iosr.statistics.tab2box and iosr.statistics.quantile). That sounds like more work than just downloading the whole toolbox (which contains only text-based files, so is very small) and adding the parent path to your Matlab path. Typing "import iosr.statistics.*" will prevent you from having to re-write any code.

**Comment by RoyiAvital** [comment]
Yea...

But `plotBox` used to be small utility everyone can use in their project.
Now it has becomes a Toolbox of Statistics.
Too Bad, because it is much more needed as a Visualization Tool.

I guess we'll have to use the latest version before this change.
Is it accessible on the Repository?

Thank You.

**Comment by chummersone** [comment]
And that toolbox provides the same utility, which you can continue to use in your projects in exactly the same way. It's just that you add a folder to your Matlab path instead of a file or two. And I only have to manage one repository instead of two.

You can still access v3.2.1 of boxPlot here: https://github.com/chummersone/boxPlot/releases/tag/v3.2.1.

**Comment by RoyiAvital** [comment]
Well,

It doesn't make sense to have all this in the PATH just for small 2 files Visualization Tool.
Usually I just include it in my University Projects.

Hence, I prefer the 2 files only.

Maybe they should co exist as 2 different project and a user can chose which to have (Maybe both).

Thank You.

**Comment by chummersone** [comment]
> It doesn't make sense to have all this in the PATH

But it's just one folder that you need to add to your PATH. The namespaces shouldn't conflict with anything else.

> Usually I just include it in my University Projects.

Once you've added it to your PATH, you can use it in any project without any extra work or duplication.

> Maybe they should co exist as 2 different project and a user can chose which to have (Maybe both).

Like I said, it was unnecessary work to have 2 projects, when this project contains one of boxPlot's dependencies (plus, boxPlot came originally from this toolbox). (Keeping them together also gives me the option to create additional dependencies in the future.) And for the price of adding a single folder to your PATH, you can use boxPlot in exactly the same way.
