### ISSUE TITLE
Regarding the delay introduced by octave band filterbank

### ISSUE THREAD

**Issue by ghamaa** [IoSR-Surrey/MatlabToolbox#9]
Hello, 
In the irStats script you decomposed the room impulse response into octave bands. Then, you compute the reverberation time RT in each band. My issue is regarding the time delay introduced by each filter, should we compensate for that delay when we compute the reverberation time in each band. 
Thank you for your help.

**Comment by chummersone** [comment]
No. The function automatically determines the start point in each band as the peak of the squared impulse response.

**Comment by ghamaa** [comment]
You computed the peak with respect to the full band room impulse response (RIR) as stated in irStats:
   peak = find(x(:,n).^2==max(x(:,n).^2)); 
If you filter RIR and there is a time delay introduced by the filter then the location of the peak will be different from that of the full band RIR.

**Comment by chummersone** [comment]
The octave-band decay measures don’t use the position of the initial peak directly. They measure the time separating the fit points.

**Comment by ghamaa** [comment]
You are correct if we assume linear phase of filters within their passband.
What about the frequency dependent direct-to-reverberation ratio (DRR). It depends on the position of the initial peak in each frequency band.

**Comment by chummersone** [comment]
ISO 3382 makes certain requirements of the octave-band filters. The filters were designed to meet those requirements.

DRR is not calculated in each octave band, only for the entire response, per the ISO 3382 standard.
